### ISSUE TITLE
Work around for 22 fields limit on case class

### ISSUE THREAD

**Issue by joyfulvillage** [aselab/scala-activerecord#27]
Hi,

Is there a work around for the limitation of 22 columns defined in case class that extends ActiveRecord?
I am trying to have field defined in the extended body but those fields could not work for JSON inception with play2. 

Many thanks

**Comment by y-yoshinoya** [comment]
The case class limit has been lifted in Scala 2.11.
[JSON serialize and deserialize](https://github.com/aselab/scala-activerecord/wiki/Serialization-and-Deserialization#json-serialize-and-deserialize) has been supported since version 0.3.1.
