### ISSUE TITLE
Replace BoneCP with HikariCP

### ISSUE THREAD

**Issue by SebastienHugues** [aselab/scala-activerecord#47]
As reported there : 

https://groups.google.com/forum/#!topic/play-framework/7PBnjiXkNuU

A lot of persons have problems with BoneCP idle connection bug in production including me (Play 2.2.2 Scala). A new kind of connection pool seems to be very promising : 

https://github.com/brettwooldridge/HikariCP

It would be a life saver if you could integrate it in scala-activerecord ?

Thanks

**Comment by y-yoshinoya** [comment]
Version 0.4.0 has been released.
