### ISSUE TITLE
Override Id type

### ISSUE THREAD

**Issue by binkabir** [aselab/scala-activerecord#60]
Hi, how can I override the id type of the ActiveRecord extended object from "long" to either "string" or "UUID"?

**Comment by a-ono** [comment]
You can use ActiveRecordBase and ActiveRecordBaseCompanion classes to do it.
A sample code is [here](https://github.com/aselab/scala-activerecord/blob/0.3.0/activerecord/src/test/scala/samples/PrimaryKeySpec.scala).

**Comment by binkabir** [comment]
Thanks, it worked very fine
