### ISSUE TITLE
database migration?

### ISSUE THREAD

**Issue by alexw668** [aselab/scala-activerecord#62]
Hi,

I have been playing with this wonderful library. With some models and records in database, I have a need to add more non-transient attributes (columns) to the model. Is there way of doing database migration like ActiveRecords in Rails can do? If so, do you have a sample or document describing how that can be done?

Thanks,
Alex

**Comment by vnicolici** [comment]
I'm not sure if it can be done with just this library.

But if you are using it in combination with the Play framework, you could use the "evolution" system from Play:

https://www.playframework.com/documentation/2.4.x/Evolutions

**Comment by alexw668** [comment]
Thanks. I will look into that system.

Alex
