### ISSUE TITLE
How to update multiple records at once?

### ISSUE THREAD

**Issue by mirelon** [aselab/scala-activerecord#64]
There is a method `forceUpdate`, but it bypasses the validations and hooks like `beforeSave()`. Is there a method that will do the same, but in a normal way, like in rails-activerecord?

The corresponding question on stackoverflow: http://stackoverflow.com/questions/29702777/how-to-mass-update-in-scala-activerecord

**Comment by a-ono** [comment]
No, there isn't such a method, and rails [update_all](http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-update_all) also does not trigger callbacks or validations.

You should update each record like this.
```scala
Document.transaction {
  Document.where(_.size < 100).foreach(_.save(throws = true))
}
```
