### ISSUE TITLE
Add 0.3.2 release notes

### ISSUE THREAD

**Issue by mirelon** [aselab/scala-activerecord#65]
Here: https://github.com/aselab/scala-activerecord/tree/master/notes the newest is 0.3.1
and in the repo: http://repo.typesafe.com/typesafe/simple/snapshots/com/github/aselab/scala-activerecord_2.11/ the newest is already 0.3.2

**Comment by a-ono** [comment]
It's a snapshot version. Version 0.3.2 is not released yet.
