### ISSUE TITLE
Use commons-validator 1.5.0 instead of 1.4.1

### ISSUE THREAD

**Issue by mirelon** [aselab/scala-activerecord#76]
Version 1.4.1 has conflicting subdependencies:
commons-beanutils 1.8.3, which includes package org.apache.commons.collections with same classes as in commons-collections 3.2.1.

commons-validator 1.5.0 uses commons-beanutils 1.9.2, which does not contain that package

**Comment by y-yoshinoya** [comment]
Thank you for your pull request.
