### ISSUE TITLE
How about a 0.3.2 release?

### ISSUE THREAD

**Issue by mattfeury** [aselab/scala-activerecord#83]
Hello,

I'm using the latest plugin with play 2.4 and it's working out very well for me locally since i did an `sbt publish-local`. however, i'm not able to deploy to the cloud because the 0.3.2 release isn't published in maven yet. I know I could package it manually but I'd rather not go down that path for a temporary fix.

Is there any timeline on when I can expect the latest version to be released to maven?

**Comment by Ralys** [comment]
Hello,

I'm in the same situation and I really would like to use the 0.3.2!!

**Comment by y-yoshinoya** [comment]
I'm really sorry.
0.3.2 has just been released.
