### ISSUE TITLE
missing rep complaint from sbt

### ISSUE THREAD

**Issue by liao0007** [aselab/scala-activerecord#88]
I am keep getting the following active record related error from sbt.

[warn] Unable to reparse com.github.aselab#scala-activerecord_2.11;0.4.0-SNAPSHOT from sonatype-snapshots, using Tue Aug 16 10:57:03 CST 2016
...

There is no 0.4 whatever related version by manual searching
[https://search.maven.org/#search%7Cga%7C1%7Cscala-activerecord]

what I am missing? and thanks in advance!

**Comment by y-yoshinoya** [comment]
Thank you for your comment.
Now published. Please Once again.
https://oss.sonatype.org/content/repositories/snapshots/com/github/aselab/scala-activerecord_2.11/0.4.0-SNAPSHOT/

**Comment by liao0007** [comment]
thx!

**Comment by liao0007** [comment]
well one more thing about activerecord plugin for play2.
it seems play2 has dropped "configuration.getOptional" method since 2.4.0
this breaks out current plugin on file ActiveRecordPlayModule.scala line 19

please correct me if wrong. thank you!

**Comment by liao0007** [comment]
just checked play framework again and found 2.6.0-M1 now has "configuration.getOptional" def in api.Configuration class.

I guess this plugin has been pumped up with 2.6.0-M1, now supporting 2.5.x?

**Comment by y-yoshinoya** [comment]
I was planning to drop support for Play 2.5.x, but I will do the following:
- Scala 2.12.x => Play 2.6.x
- Scala 2.11.x => Play 2.5.x

This is not yet supported. (Please wait...)

**Comment by liao0007** [comment]
@y-yoshinoya thank you for the effort. I just downloaded the cached plugin from my server, which could compile with 2.5.x
