### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by darrenleeweber** [aselab/scala-activerecord#90]
Using README code with a SQLite driver config; scala 2.11.8, scala-activerecord 0.4.0.

```
src/main/scala/models/Tables.scala:5:23: could not find implicit value for parameter fieldMapper: org.squeryl.internals.FieldMapper
[error] object Tables extends ActiveRecordTables {
[error]                       ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

**Comment by darrenleeweber** [comment]
Found a solution in an old closed bug at https://github.com/aselab/scala-activerecord/issues/45
https://github.com/aselab/scala-activerecord/issues/45#issuecomment-35962205

"""
Sorry, it's a documentation bug.
Please insert import com.github.aselab.activerecord.dsl._ into models/Tables.scala
"""

How about a fix for the documentation before closing this issue?  (The old issue was years ago.)

**Comment by y-yoshinoya** [comment]
Thanks. [Database Settings](https://github.com/aselab/scala-activerecord/wiki/Database-Settings) is fixed.
